services:
  org-service-db:
    image: postgres:16
    container_name: org-postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:${ORG_POSTGRES_PORT}:5432
    volumes:
      - ${DATA_PATH:-.}/data/org_postgres:/var/lib/postgresql/data
      - ${DATA_PATH:-.}/logs/org_postgres:/var/log/postgresql
    environment:
      POSTGRES_DB: ${ORG_POSTGRES_DB}
      POSTGRES_USER: ${ORG_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ORG_POSTGRES_PASSWORD}
      TZ: UTC
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ORG_POSTGRES_USER} -d ${ORG_POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ grade-net-network ]

  org-service-app:
    image: gradenet-org-service:${IMAGE_TAG:-latest}
    build:
      context: ./org-service
      dockerfile: Dockerfile
    container_name: org-service-app
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:${ORG_APP_PORT:-8081}:8081"
      - "127.0.0.1:${ORG_DEBUG_PORT:-5006}:5006"
    volumes:
      - ${DATA_PATH:-.}/logs/org_app:/logs
    depends_on:
      org-service-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://org-service-db:5432/${ORG_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${ORG_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${ORG_POSTGRES_PASSWORD}
      SERVER_PORT: ${ORG_APP_PORT:-8081}
      JWT_SECRET: ${JWT_SECRET}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    networks: [ grade-net-network ]

  user-service-db:
    image: postgres:16
    container_name: user-postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:${USER_POSTGRES_PORT}:5432
    volumes:
      - ${DATA_PATH:-.}/data/user_postgres:/var/lib/postgresql/data
      - ${DATA_PATH:-.}/logs/user_postgres:/var/log/postgresql
    environment:
      POSTGRES_DB: ${USER_POSTGRES_DB}
      POSTGRES_USER: ${USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
      TZ: UTC
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_POSTGRES_USER} -d ${USER_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ grade-net-network ]

  user-service-app:
    image: gradenet-user-service:${IMAGE_TAG:-latest}
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service-app
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:${USER_APP_PORT:-8080}:8080"
      - "127.0.0.1:${USER_DEBUG_PORT:-5005}:5005"
    volumes:
      - ${DATA_PATH:-.}/logs/user_app:/logs
    depends_on:
      user-service-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-service-db:5432/${USER_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${USER_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${USER_POSTGRES_PASSWORD}
      SERVER_PORT: ${USER_APP_PORT:-8080}
      JWT_SECRET: ${JWT_SECRET}
      ORG_SERVICE_URL: http://org-service-app:${ORG_APP_PORT:-8081}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    networks: [ grade-net-network ]


  grade-service-db:
    image: postgres:16
    container_name: grade-postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:${GRADE_POSTGRES_PORT}:5432
    volumes:
      - ${DATA_PATH:-.}/data/grade_postgres:/var/lib/postgresql/data
      - ${DATA_PATH:-.}/logs/grade_postgres:/var/log/postgresql
    environment:
      POSTGRES_DB: ${GRADE_POSTGRES_DB}
      POSTGRES_USER: ${GRADE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${GRADE_POSTGRES_PASSWORD}
      TZ: UTC
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${GRADE_POSTGRES_USER} -d ${GRADE_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ grade-net-network ]

  grade-service-app:
    image: gradenet-grade-service:${IMAGE_TAG:-latest}
    build:
      context: ./grade-service
      dockerfile: Dockerfile
    container_name: grade-service-app
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:${GRADE_APP_PORT:-8082}:8082"
      - "127.0.0.1:${GRADE_DEBUG_PORT:-5007}:5007"
    volumes:
      - ${DATA_PATH:-.}/logs/grade_app:/logs
    depends_on:
      grade-service-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://grade-service-db:5432/${GRADE_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${GRADE_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${GRADE_POSTGRES_PASSWORD}
      SERVER_PORT: ${GRADE_APP_PORT:-8082}
      JWT_SECRET: ${JWT_SECRET}
      ORG_SERVICE_URL: http://org-service-app:${ORG_APP_PORT:-8081}
      USER_SERVICE_URL: http://user-service-app:${USER_APP_PORT:-8080}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    networks: [ grade-net-network ]

networks:
  grade-net-network:
    driver: bridge