SELECT 'CREATE DATABASE org_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'org_db')\gexec
SELECT 'CREATE DATABASE user_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'user_db')\gexec
SELECT 'CREATE DATABASE grade_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'grade_db')\gexec
SELECT 'CREATE DATABASE add_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'add_db')\gexec

GRANT ALL PRIVILEGES ON DATABASE org_db TO CURRENT_USER;
GRANT ALL PRIVILEGES ON DATABASE user_db TO CURRENT_USER;
GRANT ALL PRIVILEGES ON DATABASE grade_db TO CURRENT_USER;
GRANT ALL PRIVILEGES ON DATABASE add_db TO CURRENT_USER;
