ALTER TABLE grade ADD COLUMN attempt INTEGER NOT NULL DEFAULT 1;
ALTER TABLE grade ADD COLUMN academic_year VARCHAR(9) NOT NULL DEFAULT '2026-2027';
ALTER TABLE grade ADD COLUMN semester INTEGER NOT NULL DEFAULT 1;
